Unittest for vandor-rename.py
icaropires/vandor-rename pull request #15
Opened 2019-10-06 06:27 UTC by Physsix27

# Pull Request
Unit testing the `vandor-rename.py` python file

### Targeted Issue:
  - #11 

### Pre-Pull Request Checklist:
> Ensure you pre-install `pytests` running `pip install -r tests/requirements.txt` before running the test
- [x] Run `pytest tests/unit/valid_names_test.py`

2019-10-06 06:29 UTC, Physsix27 commented
I just would like to know if this is what you want?
I will be adding more tests in different files depending on the function I test.

2019-10-06 18:29 UTC, icaropires commented
> I just would like to know if this is what you want?
> I will be add more tests in different files depending on the function I test.

Hi! Thanks for the PR :smiley: !

I updated my comment at the issue describing the desired structure.

2019-10-06 18:43 UTC, icaropires commented
About the renaming of the file, you're right, the python file name should not contain `-`, the source code file can be renamed to `vandor_rename.py` as you did.

But the repository name won't change and you can keep the name as `vandor-rename` for the binary at `/usr/local/bin/vandor-rename` at installation step and usage examples.

2019-10-06 21:12 UTC, Physsix27 commented
Great, I will continue working on the `unittest` for `vaondor_rename.py` and add coverage where we can see the % that is be covered by the tests.

2019-10-07 00:49 UTC, icaropires commented
@Physsix27 tell me when you're ready

2019-10-07 01:00 UTC, Physsix27 commented
Well as of now I prepared the test file called `vandor_rename_test.py` and integrate the `coverage report` and a `makefile` to run tasks. This can be its own PR and then I can make another PR to just writing `unit test` for each specific function inside of `vandor_rename.py`
- [ ] is_renamed_exercise()
- [ ] is_shortname_exercise()
- [ ] type_to_presentation_type()
... etc
Like this, it can be more organized and is not good to have a lot of things in a big PR

2019-10-07 02:06 UTC, icaropires commented
> @icaropires
> Well as of now I prepared the test file called `vandor_rename_test.py` and integrate the `coverage report` and a `makefile` to run tasks. This can be its own PR and then I can make another PR to just writing `unit test` for each specific function inside of `vandor_rename.py`
> 
>     * [ ]  is_renamed_exercise()
> 
>     * [ ]  is_shortname_exercise()
> 
>     * [ ]  type_to_presentation_type()
>       ... etc
>       Like this, it can be more organized and is not good to have a lot of things in a big PR

Sure! You can do that, but I'll ask to create an issue related to coverage, makefile and stuff and then reference that new issue at this PR. Thanks for adding those extra things :smiley: 

But, to save some time, I'll start a review.

2019-10-07 02:32 UTC, icaropires requested changes
If possible, fix this points too:
- [ ] Rename `makefile` to `Makefile`
- [x] Rename `requirements.txt` to `requirements-dev.txt`
- [x] Use the pattern `test_*.py` for the test files
- [x] Use `flake8` tool at the test file you created and fix the errors

Tell me when you're ready :wink:

2019-10-07 02:32 UTC, icaropires commented on makefile
> +#! usr/bin/env bash
Makefile is not a bash script, please remove this line

2019-10-07 02:32 UTC, icaropires commented on makefile
> +.PHONY: preInstall
`.PHONY` can be called just one time, please look [this](https://github.com/RasaHQ/rasa/blob/master/Makefile) example

2019-10-07 02:32 UTC, icaropires commented on makefile
> +preInstall:
Please rename the command to `install`

2019-10-07 02:32 UTC, icaropires commented on makefile
> +createVirtualenv:
Please, rename to the command `create-env`

2019-10-07 02:32 UTC, icaropires commented on makefile
> +	source env/bin/activate
You can't source files at Makefile in Linux :confused:

2019-10-07 02:32 UTC, icaropires commented on makefile
> +	pip install --upgrade pip
Change all `pip` to `pip3`, some systems still getting confused by this.

2019-10-07 02:32 UTC, icaropires commented on makefile
> +cleanReport:
Please, rename it to `clean` and also delete the `__pycache__` folders under `tests/` and at the project root and `htmlcov` folder.

2019-10-07 02:32 UTC, icaropires commented on makefile
> +openReport: cleanReport
Please, rename it to `open-report`.

2019-10-07 02:32 UTC, icaropires commented on makefile
> +	open htmlcov/index.html
`open` only work for MacOs systems. I suggest this line:
``` bash
xdg-open htmlcov/index.html || firefox htmlcov/index.html || google-chrome htmlcov/index.html
```

2019-10-07 02:54 UTC, Physsix27 commented on makefile
> +	open htmlcov/index.html
I don't think that solution would work, we can definitely fix this issue later on

2019-10-07 03:02 UTC, icaropires commented on makefile
> +	open htmlcov/index.html
Sure! But for accepting I need a command that work on Linux, that can be another line, since it works on Linux.

2019-10-07 03:18 UTC, Physsix27 commented on makefile
> +	open htmlcov/index.html
Added `open htmlcov/index.html || xdg-open  htmlcov/index.html`

2019-10-07 03:27 UTC, icaropires requested changes
You're almost there!

You just forgot to rename `makefile` to `Makefile` and:
- [x] At the installation step on README the path `https://raw.githubusercontent.com/icaropires/vandor-rename/master/vandor-rename.py` should be updated to `https://raw.githubusercontent.com/icaropires/vandor-rename/master/vandor_rename.py`

2019-10-07 03:27 UTC, icaropires commented on .flake8
> +ignore = E501
Unfortunately ignore the line length is not a option. It's a convention to keep lines short on python community.

2019-10-07 03:27 UTC, icaropires commented on makefile
> +	rm -rf .coverage
Delete also the other folders, could be like this:

```
rm -rf .coverage  htmlcov __pycache__ */__pycache__
```

2019-10-07 03:36 UTC, Physsix27 commented on .flake8
> +ignore = E501
It is a convention in python community but nowadays we developers own monitors that are 32/42 inch long and there is no necessity of having this. This is how its also done at big companies.

2019-10-07 03:42 UTC, icaropires commented on .flake8
> +ignore = E501
I understand... But for this project lets keep this rule, I like splitting my screen with Vim and this rule help me :smiley:

2019-10-07 03:45 UTC, icaropires approved these changes
Great !
Thanks for the contributions and the patience for making the adjustments! :smiley:

2019-10-07 03:46 UTC, merged