Add type annotations to every function
icaropires/vandor-rename pull request #16
Opened 2019-10-06 11:51 UTC by melko

This addresses issue #10 adding type annotations for every function in
the script.

2019-10-06 18:13 UTC, icaropires requested changes

2019-10-06 18:13 UTC, icaropires commented on vandor-rename.py
> +    def get_new_name(typee: str, ext: str = None) -> str:
Hi ! Thanks for the PR :smiley: .
There's just one detail to change, `ext` param should also be [Optional](https://docs.python.org/3/library/typing.html#typing.Optional).

Could you fix it?

2019-10-07 03:49 UTC, icaropires commented
@melko Could you please resolve the conflicts and add the requested changes?

2019-10-07 16:07 UTC, melko commented
done

2019-10-07 16:20 UTC, icaropires approved these changes

2019-10-07 16:21 UTC, icaropires approved these changes
Great! Thanks for contributing :smiley:

2019-10-07 16:21 UTC, merged