More Tests
icaropires/vandor-rename pull request #20
Opened 2019-10-11 02:27 UTC by Physsix27

### Functions  Tests
- [x] is_renamed_exercise()
- [x] is_shortname_exercise()
- [x] type_to_presentation_type()
- [x] alert_ignored_files()
- [x] alert_renamings_to_be_applied()

I will work on the next tests later on. This PR is ready.
Coverage Report for `vandor_rename.py` increase to 28%.
![image](https://user-images.githubusercontent.com/36493537/66620073-2d191980-ebad-11e9-816c-a14d31aba877.png)

2019-10-11 13:37 UTC, icaropires commented
Thanks for your efforts @Physsix27 ! But I'll point some things.

2019-10-11 14:04 UTC, icaropires requested changes
Thanks for the PR ! Alert me once you've finished the fixings :wink: . Also, I don't think that open another PR just for finishing issue #11 is a good idea :confused:

2019-10-11 14:04 UTC, icaropires commented on tests/test_vandor_rename.py
> +    Should ensure the type returned by is_renamed_exercise() is a bool
We have types annotations on functions and there exists tools which check if types are correct automatically. So I don't think we need any tests for checking types :sweat_smile: .

We need tests only to check if exceptions are raised given inputs and if output is correct given for different inputs.

2019-10-11 14:04 UTC, icaropires commented on tests/test_vandor_rename.py
> +    Should ensure the type returned by is_shortname_exercise() is a bool
We have types annotations on functions and there exists tools which check if types are correct automatically. So I don't think we need any tests for checking types :sweat_smile: .

We need tests only to check if exceptions are raised given inputs and if output is correct given for different inputs.

2019-10-11 14:04 UTC, icaropires commented on tests/test_vandor_rename.py
> +    assert result == expected_result
Make this and `test_type_to_presentation_type_return2` a unique function. You can use `parametrize test` for this, look [here](https://docs.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions) for instructions.

2019-10-11 14:04 UTC, icaropires commented on tests/test_vandor_rename.py
> +    assert vandor.alert_ignored_files(("A", 2, "C", 4)) == None
This doesn't check if something is printed, `alert_ignored_files()` will **always** return None.

2019-10-11 14:04 UTC, icaropires commented on tests/test_vandor_rename.py
> +    assert vandor.alert_renamings_to_be_applied(file_list) == None
This doesn't check if something is printed, `test_alert_renamings_to_be_applied()` will always return None.

2019-10-11 14:04 UTC, icaropires commented on tests/test_vandor_rename.py
> +    with pytest.raises(FileNotFoundError):
This test is good!

2019-10-11 20:46 UTC, Physsix27 commented on tests/test_vandor_rename.py
> +    Should ensure the type returned by is_renamed_exercise() is a bool
You don't have exceptions in all of your functions if there are no exceptions I will make tests for their return values

2019-10-11 23:04 UTC, Physsix27 commented
I need some help on testing `print() I am not sure how can I do that. How do I test that `print` has been call?

2019-10-11 23:20 UTC, icaropires commented
> I need some help on testing `print() I am not sure how can I do that. How do I test that `print` has been call?

@Physsix27 you can use `capfd` or `capsys`, more information [here](https://docs.pytest.org/en/latest/capture.html)

2019-10-12 01:55 UTC, Physsix27 commented
I am trying to use that but the thing is the way that the print is format it is killing me.
![image](https://user-images.githubusercontent.com/36493537/66692980-dd505600-ec71-11e9-85c4-d7456436e41c.png)

2019-10-12 02:06 UTC, icaropires commented
> I am trying to use that but the thing is the way that the print is format it is killing me.
> ![image](https://user-images.githubusercontent.com/36493537/66692980-dd505600-ec71-11e9-85c4-d7456436e41c.png)

Backslashes almost never are a cool thing in Python. You can use multi-line strings like:
``` python
"""This
is
a multiline string
"""
```

Or like is done at the source code:
``` python
    print('======================================\n'
          '\tRenamings to be applied:\n'
          '======================================')
```

For getting the exact match, I recommend you look in the source code the details on how the strings are assembled.

2019-10-12 02:44 UTC, Physsix27 commented
Can you declare a variable called `result_exected = ` and write to me that multi-line. I can't seem to solve that issue.

2019-10-12 05:11 UTC, Physsix27 commented
Fixed the tests for those print statements. Its anything else needs it for this PR to be fixed. Cant work on the other tests right at this moment.

2019-10-12 15:03 UTC, icaropires requested changes
Great improvement!

Can add more these changes? The main point was missing test cases for different situations.
Addionally, I'd like to ask for you to rename `input` to just `in`, as input is a reserved keyword in python.

I believe that with this we are good to go. Ping me once you've finished :wink:

2019-10-12 15:03 UTC, icaropires commented on vandor_rename.py
> -    print("The following files will be ignored because they don't"
I believe the correct form is `don't`

2019-10-12 15:03 UTC, icaropires commented on tests/test_vandor_rename.py
> +    vandor.alert_ignored_files(("A", 2, "C", 4))
Add as input some files that should not be ignored mixed with those you already added.

2019-10-12 15:03 UTC, icaropires commented on tests/test_vandor_rename.py
> +@pytest.mark.parametrize("input, expected_result", [("logico.brM3", True), ("fisico.sql", True)])
Add some test case that the function should return `False`

2019-10-12 15:03 UTC, icaropires commented on tests/test_vandor_rename.py
> +@pytest.mark.parametrize("input, expected_result", [("aula_test.brM3", True), ("fisico.sql", False)])
Add some test case that is a real name for a renamed_exercise, like: `aula1exer2Evolucao3Consulta_AlunoSobrenome_15-0129815.sql`

2019-10-12 15:12 UTC, icaropires commented on tests/test_vandor_rename.py
> +    assert expected_result, result
You must replace `,` with `==`

2019-10-12 16:19 UTC, Physsix27 commented
`in` is a special keyword in python not `input`

2019-10-12 16:45 UTC, icaropires commented
> `in` is a special keyword in python not `input`

@Physsix27 you're right. `in` is also reserved, but `input` is the function `input()` :sweat_smile: . You should use the name of the parameter, for example `renamings` for `alert_renamings_to_be_applied` function

2019-10-12 17:04 UTC, icaropires commented on tests/test_vandor_rename.py
> +    vandor.alert_ignored_files(("A", 2, "C", 4))
No, you were right, only invalid files should go here. But I can fix this.

2019-10-12 17:05 UTC, merged

2019-10-12 17:05 UTC, icaropires commented
Thanks for contributing!